### ISSUE TITLE
Expose a way to send usage information to stderr

### ISSUE THREAD

**Issue by Julian** [ewels/rich-click#164]
I was quickly evaluating switching/using this [on a project of mine](https://github.com/bowtie-json-schema/bowtie), which looks quite nice (originally I found it simply looking for a good command-group plugin for click, but given I already use rich this seems like a nice fit).

I have one main issue though from trying to drop this in -- my tests fail because usage errors seem to go to stdout rather than stderr.

Specifically if I run `bowtie non-existing-subcommand` after simply changing to `import rich_click as click` I get usage output on stdout.

I see the README mentions that the rich console I can modify is *separate* from the one used internally. It seems the internal one is the one that needs modifying to change this behavior. Looking at the code, I see there's a [create_console](https://github.com/ewels/rich-click/blob/main/src/rich_click/rich_help_formatter.py#L20) that takes a `file` where I'd love to pass `sys.stderr`, but as far as I can quickly tell there's nothing that calls that, and/or no way I can actually pass that argument through via `rich.click_config()`. Alternatively I don't quite see a way to inject a `RichHelpFormatter`.

Apologies if this exists and I've missed it. I'm happy to send a PR if need be, though to do so I'd love to know whether the current behavior (sending to stdout) is intentional / whether you want to keep it, and if so but you still would support some way of changing where it goes, whether the intention is to expose `create_console` somewhere or else to only expose `file` directly via `click_config`.

Thanks!

**Comment by dwreeves** [comment]
Hi @Julian, thank you for opening this issue!

> but as far as I can quickly tell there's nothing that calls that

Yep, that's a bug that I noticed and will be fixed in 1.8.0. I am already working on that.

> I have one main issue though from trying to drop this in -- my tests fail because usage errors seem to go to stdout rather than stderr.

One of rich-click's objectives is to be a seamless drop-in that mimics click. In this case, there is a disparity between how rich-click emulates click, and is thus a bug.

I think I/we can fix this as part of a patch release to 1.7.x.

If you want to do a PR based on the "1.7.x" branch, I can merge it in and release it!

If you'd rather me work on it, I won't be able to get to this until next weekend.

**Comment by Julian** [comment]
Thanks for the response! Very glad to hear.

I'll give it a quick look.

> One of rich-click's objectives is to be a seamless drop-in that mimics click. In this case, there is a disparity between how rich-click emulates click, and is thus a bug.

**Comment by Julian** [comment]
Thanks for the response! Very glad to hear.

I'll give it a quick look.

> One of rich-click's objectives is to be a seamless drop-in that mimics click. In this case, there is a disparity between how rich-click emulates click, and is thus a bug.

Great! OK. Then I'll also mention the other more minor issue, which is that switching also requires me to dot in at least a bunch of calls to `textwrap.dedent` -- otherwise my help strings end up with strange internal indentation. I assume that also then might be something you'd consider a bug? I haven't looked at which ones end up needing it, but at very least [my epilogue](https://github.com/bowtie-json-schema/bowtie/blob/db319ae41b138245b8caf7419bfda97254554b6c/bowtie/_cli.py#L88-L95).

**Comment by Julian** [comment]
Sent a PR for this one. Making the epilogue match closer looks a bit trickier it seems, I'm not sure what the idiomatic way in rich is to both reflow the text (so it stretches to whatever the width is) while also dedenting. Specifically, my epilog is having its whitespace messed with a bit (because I see that `rich-click` does `split("\n\n")`, but that will remove my intentional extra newline -- I could of course add yet another one, but that makes the source text a bit funny looking). Will wait to hear what you think on that one but at least this specific issue I think should be fixed with the one liner in the PR.

Thanks again!

**Comment by dwreeves** [comment]
@Julian Can you try `rich-click==1.8.0dev2`? I think this issue should be fixed in that.

**Comment by Julian** [comment]
Hey! Thanks for the ping (and efforts!). It looks like I still have some failing tests if I switchover -- https://github.com/bowtie-json-schema/bowtie/actions/runs/8631991053/job/23661594967 -- I'm on vacation so I'm a bit slow to check why but an initial look suggests that at least one reason seemingly is the `Usage: `line still being sent to stdout. Specifically I see:

```
~/Development/bowtie is a git repository on rich-click 
⊙  bowtie run --dialect ";;;;;" -i no-such-image 2>/dev/null                                                                                                                                                                                                                                                      julian@Airm ●
                                                                                                                        
 Usage: bowtie run [OPTIONS] [INPUT]                                                                                    
```

(where that command ends up raising a `click.UsageError` for the `--dialect` option being nonsense).

**Comment by dwreeves** [comment]
No thank you for checking!

Sorry, should've checked more carefully on my end.

This one is tricky to write a clean and elegant abstraction for because of how base Click handles printing of error messages... 😅 I'll take another stab at it shortly! Getting stderr and stdout sorted out is a hard requirement for releasing 1.8.0. (Then at some point down the line I'll rewrite our unit tests to make sure the behavior is asserted.)

**Comment by dwreeves** [comment]
@Julian Ok, pinky promise this time it _should_ work. I tested and it's great!

```shell
pip install rich-click==v1.8.0dev4
```

Using the code example I described a few weeks ago in my comment: https://github.com/ewels/rich-click/pull/166#issuecomment-1989895934

```python
>>> from subprocess import Popen, PIPE
>>> process = Popen(["python", "foo.py", "--fake-flag"], stdout=PIPE, stderr=PIPE)
>>> stdout, stderr = process.communicate()
>>> print(f"{len(stdout)=}", f"{len(stderr)=}")
len(stdout)=0 len(stderr)=112
>>> print(stderr)
b"Usage: foo.py [OPTIONS] FOO COMMAND [ARGS]...\nTry 'foo.py --help' for help.\n\nError: No such option: --fake-flag\n"
```

Thanks for opening the issue. I'll close once you've confirmed everything's fine.

The stable release of `rich-click` is slated to be finalized no later than the first week of May, FWIW.

**Comment by Julian** [comment]
Fantastic, thanks again! This indeed seems like it works here!

**Comment by dwreeves** [comment]
Great! I'll close the issue then as completed.

**Comment by Julian** [comment]
I haven't gotten a chance yet to put together a minimal example, but I think this behavior regressed in 1.8.5 -- specifically my tests went back to failing. I'll try to have a closer look to see why and file an issue.

**Comment by dwreeves** [comment]
@Julian Ahhhh! Sorry, we never covered this with tests. I believe it when you say it regressed because I believe 1.8.5 touched something that would impact this behavior. I'll look into it.

**Comment by dwreeves** [comment]
Hi @Julian, sorry for radio silence on this. My life is very busy, but I'm trying to get back into the swing of things...

Can you please check out the prerelease version `1.8.7a0` and see if it resolves the issue? 😃

**Comment by Julian** [comment]
Absolutely 0 worries and I hear you on life :/ -- hope all's well! And deeeeefinitely appreciate the follow-up! I'll give it a shot tomorrow!

**Comment by Julian** [comment]
@dwreeves that doesn't seem to fix things here unfortunately. Specifically usage info still seems to be going to stdout now, not stderr.

In my case, on anything <=1.8.4, usage info for a broken command goes to stderr:

```
⊙  .nox/tests-3-13/bin/bowtie run --dialect some://nonexisting/thing >/dev/null                                                                                                                                                                                                                                                                                   julian@Mac
                                                                                                                        
 Usage: bowtie run [OPTIONS] [INPUT]                                                                                    
                                                                                                                        
 Try 'bowtie run --help' for help                                                                                       
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--dialect' / '-D': 'some://nonexisting/thing' is not a known dialect URI or short name.           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                                                                                                                        
```

as it did when I was using click which I think we diagnosed in this PR.
But on any successive version (including `1.8.7dev0`), it seems to go to stdout:

```
~/Development/bowtie is a git repository on main 
⊙  uv pip install --python .nox/tests-3-13/bin/python rich-click==1.8.7dev0                                                                                                                                                                                                                                                                                       julian@Mac
Using Python 3.13.2 environment at: .nox/tests-3-13
Resolved 7 packages in 12ms
Uninstalled 1 package in 1ms
Installed 1 package in 4ms
 - rich-click==1.8.4
 + rich-click==1.8.7.dev0

~/Development/bowtie is a git repository on main 
⊙  .nox/tests-3-13/bin/bowtie run --dialect some://nonexisting/thing >/dev/null                                                                                                                                                                                                                                                                                   julian@Mac

```

(no output at the bottom).

**Comment by dwreeves** [comment]
@Julian Thanks for testing, let me look into it a bit more! I wasn't 100% sure if my changes fixed, hence why I pushed the change as a pre-release.

**Comment by dwreeves** [comment]
Hi @Julian, are you sure that you were running `1.8.7.dev0` with your test? I'm not able to figure out the issue.

Minimal reproducible example:

```python
# hello.py
import rich_click as click

@click.command()
def cli():
    """Test app"""

if __name__ == "__main__":
    cli()
```

Test:

```
>>> python hello.py --bad-input >/dev/null || echo done
                                                                                          
 Usage: hello.py [OPTIONS]                                                                
                                                                                          
 Try 'hello.py --help' for help                                                           
╭─ Error ────────────────────────────────────────────────────────────────────────────────╮
│ No such option: --bad-input                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────╯
                                                                                          
done
```

This behavior is controlled by line 173 in `rich_command.py`. When I remove the `file=sys.stderr` arg from that line:

```
>>> python hello.py --bad-input >/dev/null || echo done
done
```

So, I think I will release version `1.8.7` as is because I believe the issue is solved, unless I am missing something.

**Comment by Julian** [comment]
The bug is in the other branch there I think, on line [170 where ctx is indeed not None](https://github.com/ewels/rich-click/blob/87aa8e82bc2060f07f5fbdb54e0710ada469bce8/src/rich_click/rich_command.py#L170) so in a subcommand or something.

So a reproducer looks like:

```python
⊙  cat foo.py                                                                                                                                                                                                                                                                                                                                                   julian@Mac ●
import rich_click as click

class Dialect(click.ParamType):
    def convert(self, value, _, __) -> None:
        self.fail(f"{value!r} is not a known dialect URI or short name.")

@click.group()
def cli():
    pass

@click.option("--dialect", type=Dialect())
@click.pass_context
def bar(ctx, dialect):
    pass

if __name__ == "__main__":
    cli()


~/Desktop 
⊙  uv run --with 'rich-click==1.8.4' foo.py bar --dialect foo >/dev/null                                                                                                                                                                                                                                                                                        julian@Mac ●
                                                                                                                                                                                                                                                                                                                                                                             
 Usage: foo.py [OPTIONS] COMMAND [ARGS]...                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                             
 Try 'foo.py --help' for help                                                                                                                                                                                                                                                                                                                                                
╭─ Error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'bar'.                                                                                                                                                                                                                                                                                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                                                                                                                                                                                                                                                                                                                                                                             

~/Desktop 
⊙  uv run --with 'rich-click==1.8.7' foo.py bar --dialect foo >/dev/null                                                                                                                                                                                                                                                                                        julian@Mac ●

```

**Comment by dwreeves** [comment]
Ah, got it.

Thank you for your patience and your assistance on this @Julian. I'll not only fix this today, but I have finally done what I should have done a while ago: I've add a unit test to cover this case explicitly. 😆 Both for groups and commands.

**Comment by Julian** [comment]
I've done nothing but been lazy at filing a decent minimal reproducer until now, so no need to thank me :)

Appreciate all your work!!
